### ISSUE TITLE
Contour 0.4.0 Release Checklist

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#1273]
### Before we release

- [x] CSIu: meta key still transmitted for `CSI > 1 u`?
- [x] #1276
- [x] #1293
- [x] Is the Win32 CI binary executable?
- [x] Fix CI for quick exit
- [x] #1228 MacOS/X DMG's installed exe can't execute? (there's some dependency missing due to QML merge)
- [x] dpi change (also by monitor change) screws up font size in terminal
- [ ] #1366

Am I missing anything?

**Comment by Yaraslaut** [comment]
I checked both zip and msi from master builds for windows

**Comment by Yaraslaut** [comment]
We need to fix https://github.com/contour-terminal/libunicode/issues/79 to build on Ub 20.04
