### ISSUE TITLE
Code Cleanup refactorings

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#300]
### Tracker ticket

**NOTE: I am going to update the ticket body with action items as I find them, over the time.**

- [ ] shared namespace contour, and put frontend into contour::frontend.
- [x] Replace `crispy::range` with ranges V3 `subrange` or `gsl::span` (see: [GSL](https://github.com/microsoft/GSL))
- [x] `crispy::times` can be replaced with `ranges::views::iota(start, end)` from range-v3
- [ ] refactor config loading to make it fully testible
- [x] add proper errrorlog()
- [ ] also have a facility for warnings. Maybe we can provide an interface like ErrorReporter that can be implemented to log to stout, istream (file) or GUI elements 
- [x] kill dead code / files (eg. Size_test.cpp)
- [x] reduce warning count in pedantic mode!
- [ ] `text_shaper` library should not depend on `crispy` support library (except for the `boxed<T>` type), so that in theory this lib could be extracted into its own repo under the `github.com/contour-terminal/`-namespace (just like libunicode).
- [ ] `text_shaper`: move run segmentation (`unicode::run_segmenter`) calls into this interface, as on windows we might want to use the DirectWrite versions (optionally).
- [x] increasing code coverage using unit tests
- [ ] evaluate using [WIL](https://github.com/microsoft/wil) on Windows platform
- [ ] ...

**Comment by data-man** [comment]
> gsl::span

with `std::span` if available?

**Comment by christianparpart** [comment]
> 
> 
> > gsl::span
> 
> with `std::span` if available?

I do favor stdlib where possible. But that'll take a while until std::span is broadly available (osx/msvc/linux, down to ubuntu 18.04 PPA). I think `gsl::span` is a good compromise (currently I created my own basic one in `crispy::span<T>`). I just hope that `gsl::span` is API compatible to `std::span` (didn't verify that).

**Comment by data-man** [comment]
What else can be useful from gsl?
What about https://github.com/martinmoene/span-lite?

**Comment by christianparpart** [comment]
> What else can be useful from gsl?
> What about https://github.com/martinmoene/span-lite?

- zstring-family,
- owner
- not_null (I currently use crefs/refs for that)
- finally (I can then get rid of the one in crispy lib)
- narrow_cast
- Expects/Ensures: I am currently having some sanity checks especially in Screen class to ensure integrity, these helpers might improve readability maybe, at least worth exploring and maybe also aiding FV tools in the future.

Sure, we shouldn't do all in one PR, but in small-ish steps. I favor embracing the C++ core guidelines as well as clean maintainable code (I know, I am certainly everything but not perfect, so contour surely is having its dark corners, a few of them I am aware of. Maybe we can converge to that goal at least.

One thought on performance (I think we didn't bring this up yet). I certainly do care about performance - as much as it doesn't hurt maintainability and clean-ness of the code base.

**Comment by WSLUser** [comment]
GSL is a good standard to stick with. There's a gsl-lite project in addition to that span-lite but your best bet is to stick with using GSL wherever possible. It's would also be good to use WIL for the Windows port.

**Comment by WSLUser** [comment]
I have another good item: Evaluate updating https://github.com/contour-terminal/contour/blob/master/src/terminal/ (and any other libraries in this repo) with content from https://github.com/microsoft/terminal/tree/main/src/inc/til (and their tests at https://github.com/microsoft/terminal/tree/main/src/til/ut_til). `Color.h` for example, could likely benefit from the optimizations Windows Terminal made (it's as performant as it can get) and from there, update things like `Sixel.h`.

**Comment by christianparpart** [comment]
closing, most is done, some items went into a different way by now. nothing else to be done here :)
