### ISSUE TITLE
[Tracker] Improve caching layers

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#351]
by making use of LRU caching whenever possible (note, currently it's either naive caching, or simple `shared_ptr<>`'s)

## Checklist

* [x] use it for glyph caching
* [x] use it for caching text shaping result
* [x] use it for hyperlink (OSC 8) caching
* [x] use it for grid cell's ImageFragment caching, too.

The goal of using LRU caching (instead of `shared_ptr`) in the `Cell` structure is to attempt to get it trivially copyable.

Generally however it helps mitigating malicious resource excess.

**Comment by christianparpart** [comment]
Done.
PL m look
