### ISSUE TITLE
release 0.2.0 checklist tracker

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#392]
- [x] ensure after emoji, the cursor cursory is moved by its emoji width, usually 2!
- [x] ensure notcurses-info cubs and renders ask glyphs correctly
- [x] OS/X installer and its CI working again
- [x] maybe fix glyph have #381 texture cache excess?
- [x] have #381 and #388 implemented/fixed

This release is not meant to be perfect. Known bugs will not all be fixed immediately, but can eventually find as point release later.
