### ISSUE TITLE
pixel perfect box drawing tracker ticket

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#441]
This ticket purely serves as tracker of what codepoint ranges have been implemented (or taken care of) with regards to pixel perfect box drawing already, so that we have have them all implemented in small consecutive PRs rather than one huge one. 

# Checklist

- [x] 1FB00..1FB3B block sextants (notcurses++)
- [ ] 1FB3C..1FB6F Smooth mosaic terminal graphic characters
- [ ] 1FB70..1FB8B block elements
- [ ] 1FB8C..1FB94 Rectangular shade characters
- [ ] 1FB95..1FB99 Fill characters
- [ ] 1FB9A..1FB9B Smooth mosaic terminal graphic characters
- [ ] 1FB9C..1FB9F Triangular shade characters
- [ ] 1FBA0..1FBAE Character cell diagonals
- [ ] 1FBAF..1FBAF Light solid line with stroke
- [ ] 1FBB0..1FBB3 Terminal graphic characters  (are they all useful???)
- [ ] 1FBB4..1FBB8 Arrows (are they all useful???)
- [ ] 1FBB9..1FBBC Terminal graphic characters
- [ ] 1FBBD..1FBBF Negative terminal graphic characters
- [ ] 1FBC0..1FBCA Terminal graphic characters (are they all useful???)
- [ ] 1FBF0..1FBF9 Segmented digits (fonts are fine for that???)
- [x]  2500..257F standard box drawing (was already present)
- [x]  2580..2590 block elements
- [ ]  2591..2593 shade characters
- [x]  2594..2595 block elements
- [ ]  2596..259F Terminal graphic characters
