### ISSUE TITLE
Explore migration to QML

### ISSUE THREAD

**Issue by christianparpart** [contour-terminal/contour#752]
### Challenges

- [ ] Actually making use of QML with custom OpenGL widgets seems very hard (to me!)
- [ ] how to set minimum item size (no setMinimumSize)
- [ ] no access to logical/physical DPI information?
- [ ] No `updateGeometry()`?
- [ ] How to implement toggling the titlebar (feature)?
- [ ] how to `QApplication::beep()`
- [ ] How to create a QMessageBox::question equivalent in QML that yields a result on what button was pressed?

### Motivations
- [ ] Have terminal view as QML object, including its scrollbar and potential overlays (scrollbar, error messages) all defined from within QML source.
- [ ] Have tabs and have them in the main title bar and have them styled and colorizable, movable
- [ ] have split views
